Currently Loaded Modulefiles:
  1) gcc-libs/4.9.2                   13) giflib/5.1.1
  2) cmake/3.21.1                     14) emacs/28.1
  3) flex/2.5.39                      15) tmux/3.2a
  4) git/2.32.0                       16) mrxvt/0.5.4
  5) apr/1.7.0                        17) userscripts/1.4.0
  6) apr-util/1.6.1                   18) rcps-core/1.0.0
  7) subversion/1.14.1                19) default-modules/2018
  8) screen/4.8.0-ucl1                20) compilers/gnu/4.9.2
  9) gerun                            21) cuda/10.1.243/gnu-4.9.2
 10) nano/2.4.2                       22) python/3.8.6
 11) nedit/5.6-aug15                  23) openblas/0.3.7-serial/gnu-4.9.2
 12) dos2unix/7.3                     24) python3/3.8
/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/spikeinterface/sorters/waveclus/waveclus.py:124: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='UTF-8'>
  if cls.check_compiled():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2022-10-26 12:38:24 INFO     Starting
2022-10-26 12:38:24 INFO     at main function
2022-10-26 12:38:24 INFO     variable: BlockNellie-1
2022-10-26 12:38:28 INFO     variable: BlockNellie-2
2022-10-26 12:38:30 INFO     variable: BlockNellie-3
2022-10-26 12:38:31 INFO     variable: BlockNellie-4
2022-10-26 12:38:31 INFO     variable: BlockNellie-5
2022-10-26 12:38:32 INFO     variable: BlockNellie-6
Traceback (most recent call last):
  File "/home/zceccgr/Scratch/zceccgr/spikeinterface3cg/interfacetest_jules_cg_kilosort_concatenate_ms4_crumble.py", line 251, in <module>
    main()
  File "/home/zceccgr/Scratch/zceccgr/spikeinterface3cg/interfacetest_jules_cg_kilosort_concatenate_ms4_crumble.py", line 219, in main
    new_data = preprocess_data_cg(data)
  File "/home/zceccgr/Scratch/zceccgr/spikeinterface3cg/interfacetest_jules_cg_kilosort_concatenate_ms4_crumble.py", line 119, in preprocess_data_cg
    recording = se.CustomTdtRecordingExtractor(data.dp, store=data.store)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/customtdt.py", line 21, in __init__
    NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id, **neo_kwargs)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 27, in __init__
    _NeoBaseExtractor.__init__(self, **neo_kwargs)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 17, in __init__
    self.neo_reader.parse_header()
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/neo/rawio/baserawio.py", line 185, in parse_header
    self._parse_header()
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/neo/rawio/customtdtrawio.py", line 107, in _parse_header
    self._tdt_data = tdt.read_block(tdt_folder,store=self.store)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/tdt/TDTbin2py.py", line 1667, in read_block
    sev_names = read_sev(block_path, just_names=True)
  File "/lustre/home/zceccgr/spkenv2/lib/python3.8/site-packages/tdt/TDTbin2py.py", line 326, in read_sev
    stream_header.size_bytes   = np.fromfile(sev, dtype=np.uint64, count=1)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
tar: Removing leading `/' from member names
